### ISSUE TITLE
`/corpus_config`: Non-existent mode results in TypeError “'NoneType' object does not support item assignment”

### ISSUE THREAD

**Issue by janiemi** [spraakbanken/korp-backend#12]
Calling `/corpus_config` with a non-existent mode gives the `TypeError` “'NoneType' object does not support item assignment”, which I don’t find descriptive of the actual error. For example: https://ws.spraakbanken.gu.se/ws/korp/dev/corpus_config?mode=test

This happens because `get_mode` returns `None` on `FileNotFoundError`:
https://github.com/spraakbanken/korp-backend/blob/229b2744d450976704718744e4eee1819b125986/korp.py#L3414-L3418 and `corpus_config` tries to assign to a key of the returned value: https://github.com/spraakbanken/korp-backend/blob/229b2744d450976704718744e4eee1819b125986/korp.py#L3365-L3366

I think this would be easy to fix, but I didn’t yet create a pull request as I don’t know if you have your preferences on what kind of an error message to return.

**Comment by MartinHammarstedt** [comment]
Thanks! This is now fixed in 5dfb61c.
