### ISSUE TITLE
API docs for /query missing corpus_order, query_data

### ISSUE THREAD

**Issue by arildm** [spraakbanken/korp-backend#22]
Responses from `/query`, e.g. https://ws.spraakbanken.gu.se/ws/korp/v8/query?corpus=COCTAILL&cqp=[lemma%20contains%20%22.*%3Fspade.*%22] contain `corpus_order` and `query_data` but these are not documented on https://ws.spraakbanken.gu.se/docs/korp#tag/Concordance/paths/~1query/get

**Comment by MartinHammarstedt** [comment]
Fixed in f76fb4e.
